import type { Metadata } from "next";
import "../styles/tailwind.css";
import { DM_Sans } from "next/font/google";

const DMSansFont = DM_Sans({
  variable: "--dm-sans-font",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Bento Grid - Challenge from Frontend Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSansFont.className} bg-[#F6F5F6] font-primary`}>
        {children}
      </body>
    </html>
  );
}
